### PR TITLE
reformat the first 3 groups of the UUID

### PR DESCRIPTION
**Pull request by mbelur**
reformat to match the uuid shown by the dmidecode output

Issue: UUID of a virtual machine as shown by the dmidecode output
does not match as reported by the virtual-host-gatherer
for hardware versions >=13 in VMWare environment.

Example:
On a virtual machine with hardware version 13:

localhost:~ # dmidecode -s system-uuid
1b4e2242-b3f0-55bd-39c2-263f3860836f

virtual-host-gatherer reports:
42224e1b-f0b3-bd55-39c2-263f3860836f

This code change in virtual-host-gatherer fixes this issue
so we can match the system in SCC correctly.

After this change is applied, virtual-host-gatherer shows:
1b4e2242-b3f0-55bd-39c2-263f3860836f

### CODE REVIEW

**Comment by mcalmer** [comment]
Reference https://kb.vmware.com/s/article/53609

**Comment by moio** [comment]
According to the reference above, it sounds like `dmidecode` is not returning correct UUIDs, and that suggests we should rather fix the problem Salt grains and/or `SUSEConnect` to avoid `dmidecode` use or work around broken UUIDs there.

What advantages and disadvantages do you see in working around the problem in `virtual-host-gatherer`?

**Comment by rtamalin** [comment]
> According to the reference above, it sounds like `dmidecode` is not returning correct UUIDs, and that suggests we should rather fix the problem Salt grains and/or `SUSEConnect` to avoid `dmidecode` use or work around broken UUIDs there.
> 
> What advantages and disadvantages do you see in working around the problem in `virtual-host-gatherer`?

I agree - the issue is that the value reported by dmidecode is not correct and doesn't match what the VMWare management software intended the UUID to; it isn't "decoding" the big endian encoded parts of the UUID value appropriately.

Therefore we probably should be trying to address the issue at the point when it is being "sampled" within the VM.

That said, there may be some benefit to extending the virt-host-gatherer to report the "incorrect" value as an alternate alias value to assist in correlating SCC registrations with VMWare management software reported values..

**Comment by jdelvare** [comment]
> I agree - the issue is that the value reported by dmidecode is not correct and doesn't match what the VMWare management software intended the UUID to; it isn't "decoding" the big endian encoded parts of the UUID value appropriately.

As the maintainer of dmidecode, I have to disagree ;-)

dmidecode is interpreting the UUID bytes according to the SMBIOS specification. It turns out that the specification changed with version 2.6. Prior to that, there was no indication of how the UUID bytes should be decoded, so the network byte order was used (that means no byte swapping, in accordance with RFC 4122). In SMBIOS specification version 2.6, the UUID field description was clarified and little-endian encoding (and thus decoding) was made mandatory for the first three field of the UUID. The claim was made that this was already the de facto standard, which in my experience it wasn't, hence the confusion.

In order to not break compatibility with older systems but still comply with the latest version of the SMBIOS specification, it was decided to make the decoding of the UUID dependent on the SMBIOS version. If version is 2.5 or older, network byte order is used. If version is 2.6 or newer, little-endian byte order is used. The same is done in the kernel itself.

What happens here is that VMWare used to encode the DMI table of their guests under SMBIOS version 2.4 (if I remember correctly), but have moved to version 2.7 at some point. When doing that, they should have changed the way they encode the UUID in the table, but they did not. So from my perspective the bug is in the encoded DMI data, and has to be fixed by VMWare. But obviously this will be painful to change now if there are many such systems out in the wild already.

**Comment by moio** [comment]
@jdelvare thanks for the insights, I think I get where you are coming from.

Just to double check my understanding: your statements imply that neither `dmidecode` nor the kernel are going to change this behavior, because doing so would deviate from the SMBIOS standard (versions 2.6 and above). Hence, until VMWare addresses the issue, all users of UUIDs (including this project) will have to implement some kind of workaround.

Is this correct?

**Comment by jdelvare** [comment]
> Just to double check my understanding: your statements imply that neither `dmidecode` nor the kernel are going to change this behavior, because doing so would deviate from the SMBIOS standard (versions 2.6 and above).

Yes, this is correct.

> Hence, until VMWare addresses the issue, all users of UUIDs (including this project) will have to implement some kind of workaround.

Indeed. Unfortunately, if you work around the issue now, and then VMWare addresses the issue properly, you'll have to remove your workaround, and it might be difficult to figure out when the workaround is still needed and when not. Hopefully you have access to fine-grained version information to make the decision.

**Comment by moio** [comment]
Thanks @jdelvare, [at least in this context](https://github.com/uyuni-project/virtual-host-gatherer/pull/20/files#diff-017c0f2242a27da70c2d47415339c53b968e6c44ef854f9589cfab53a1166b9fR206) we do have that bit of information.

I am still not completely convinced this is the right approach though - intentionally breaking pyvmomi's otherwise correct output in order to match dmidecode's known incorrect output (not implying it's dmidecode's fault, just clarifying it's not the expected one/the one customers will see from VMWare's UI).

@mbelur, @rtamalin: what would be the implications of changing SUSEConnect and/or SCC's matching instead?

@cbosdo, @mcalmer: what would be the implications of changing Salt and/or SUSE Manager Server's matching instead?

**Comment by moio** [comment]
FTR: decision is that `virtual-host-gatherer` will report the mangled UUID as proposed in the current patch in addition to the correct UUID in a separate field for the time being.

**Comment by mbelur** [comment]
> FTR: decision is that `virtual-host-gatherer` will report the mangled UUID as proposed in the current patch in addition to the correct UUID in a separate field for the time being.

Updated the PR based on this decision

**Review by moio — APPROVED** [review]

**Comment by mbelur** [comment]
@cbosdo could you please take look at the change again?

**Review by cbosdo — APPROVED** [review]
👍🏻

**Pull request merged**
